app:
    resource: "@AppBundle/Controller/"
    type:     annotation
login:
  path: login/
  defaults: {_controller: AppBundle:Security:login}
logout:
  path: logout


administration:
  path: administration/
  defaults: {_controller: AppBundle:Administration:userIndex}
userIndex:
  path: administration/user/
  defaults: {_controller: AppBundle:User:index}
addUser:
  path: administration/user/add/
  defaults: {_controller: AppBundle:User:add}
  methods:  [GET, POST]
editUser:
  path: administration/user/edit/{id}
  defaults: {_controller: AppBundle:User:edit}
  methods:  [GET, POST]
deleteUser:
  path: administration/user/del/{id}
  defaults: {_controller: AppBundle:User:delete}
customerIndex:
  path: administration/customer/
  defaults: {_controller: AppBundle:Customer:index}
addCustomer:
  path: administration/customer/add/
  defaults: {_controller: AppBundle:Customer:add}
  methods:  [GET, POST]
editCustomer:
  path: administration/customer/edit/{id}
  defaults: {_controller: AppBundle:Customer:edit}
  methods:  [GET, POST]
deleteCustomer:
  path: administration/customer/del/{id}
  defaults: {_controller: AppBundle:Customer:delete}
adminIndex:
  path: administration/admin/
  defaults: {_controller: AppBundle:Administration:adminIndex}
employeeIndex:
  path: administration/employeeIndex/
  defaults: {_controller: AppBundle:Administration:employeeIndex}

order:
  path: orders/
  defaults: {_controller: AppBundle:Order:orderIndex}
orderIndex:
  path: orders/order/
  defaults: {_controller: AppBundle:Order:orderIndex}
activeOrderIndex:
  path: orders/activeOrder/
  defaults: {_controller: AppBundle:Order:activeOrderIndex}
orderHistoryIndex:
  path: orders/history/
  defaults: {_controller: AppBundle:Order:historyIndex}

myProfileIndex:
  path: myprofile/
  defaults: {_controller: AppBundle:MyProfile:index}