app:
    resource: "@AppBundle/Controller/"
    type:     annotation
login:
  path: login/
  defaults: {_controller: AppBundle:Security:login}
logout:
  path: logout


administration:
  path: administration/
  defaults: {_controller: AppBundle:Administration:userIndex}
userIndex:
  path: administration/user/
  defaults: {_controller: AppBundle:User:index}
addUser:
  path: administration/user/add/
  defaults: {_controller: AppBundle:User:add}
  methods:  [GET, POST]
editUser:
  path: administration/user/edit/{id}
  defaults: {_controller: AppBundle:User:edit}
  methods:  [GET, POST]
deleteUser:
  path: administration/user/del/{id}
  defaults: {_controller: AppBundle:User:delete}
customerIndex:
  path: administration/customer/
  defaults: {_controller: AppBundle:Customer:index}
addCustomer:
  path: administration/customer/add/
  defaults: {_controller: AppBundle:Customer:add}
  methods:  [GET, POST]
editCustomer:
  path: administration/customer/edit/{id}
  defaults: {_controller: AppBundle:Customer:edit}
  methods:  [GET, POST]
deleteCustomer:
  path: administration/customer/del/{id}
  defaults: {_controller: AppBundle:Customer:delete}
adminIndex:
  path: administration/admin/
  defaults: {_controller: AppBundle:Administration:adminIndex}
addAdmin:
  path: administration/admin/add/
  defaults: {_controller: AppBundle:Administration:addAdmin}
  methods:  [GET, POST]
deleteAdmin:
  path: administration/admin/del/{id}
  defaults: {_controller: AppBundle:Administration:deleteAdmin}
employeeIndex:
  path: administration/employee/
  defaults: {_controller: AppBundle:Employee:index}
addEmployee:
  path: administration/employee/add/
  defaults: {_controller: AppBundle:Employee:add}
  methods:  [GET, POST]
editEmployee:
  path: administration/Employee/edit/{id}
  defaults: {_controller: AppBundle:Employee:edit}
  methods:  [GET, POST]
deleteEmployee:
  path: administration/Employee/del/{id}
  defaults: {_controller: AppBundle:Employee:delete}
usergroupIndex:
  path: administration/usergroup/
  defaults: {_controller: AppBundle:Usergroup:Index}
addUsergroup:
  path: administration/usergroup/add/
  defaults: {_controller: AppBundle:Usergroup:add}
  methods:  [GET, POST]
editUsergroup:
  path: administration/usergroup/edit/{id}
  defaults: {_controller: AppBundle:Usergroup:edit}
  methods:  [GET, POST]
deleteUsergroup:
  path: administration/usergroup/del/{id}
  defaults: {_controller: AppBundle:Usergroup:delete}
userPrivilegeIndex:
  path: administration/userprivilege/
  defaults: {_controller: AppBundle:UserPrivilege:index}
saveUserPrivilege:
  path: administration/userprivilege/saveuserprivilege/
  defaults: {_controller: AppBundle:UserPrivilege:saveUserPrivilege}
orders:
  path: orders/
  defaults: {_controller: AppBundle:Order:orderIndex}
orderIndex:
  path: orders/order/
  defaults: {_controller: AppBundle:Order:orderIndex}
activeOrderIndex:
  path: orders/activeOrder/
  defaults: {_controller: AppBundle:Order:activeOrderIndex}
orderHistoryIndex:
  path: orders/history/
  defaults: {_controller: AppBundle:Order:historyIndex}

myProfileIndex:
  path: myprofile/
  defaults: {_controller: AppBundle:MyProfile:index}