app:
    resource: "@AppBundle/Controller/"
    type:     annotation
login:
  path: login/
  defaults: {_controller: AppBundle:Security:login}
logout:
  path: logout


administration:
  path: administration/
  defaults: {_controller: AppBundle:Administration:userIndex}
userIndex:
  path: administration/user/
  defaults: {_controller: AppBundle:User:userIndex}
addUser:
  path: administration/user/add/
  defaults: {_controller: AppBundle:User:add}
  methods:  [GET, POST]
editUser:
  path: administration/user/edit/{id}
  defaults: {_controller: AppBundle:User:edit}
  methods:  [GET, POST]
deleteUser:
  path: administration/user/del/{id}
  defaults: {_controller: AppBundle:User:delete}
customerIndex:
  path: administration/customer/
  defaults: {_controller: AppBundle:Administration:customerIndex}


order:
  path: order/
  defaults: {_controller: AppBundle:Order:orderIndex}
orderIndex:
  path: order/order/
  defaults: {_controller: AppBundle:Order:orderIndex}
activeOrderIndex:
  path: order/activeOrder/
  defaults: {_controller: AppBundle:Order:activeOrderIndex}
orderHistoryIndex:
  path: order/history/
  defaults: {_controller: AppBundle:Order:historyIndex}
