# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\TUser:
            algorithm: bcrypt

    providers:
    #    in_memory:
    #        memory: ~
        our_db_provider:
            entity:
                class: AppBundle:TUser
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                login_path: login
                check_path: login
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            provider: our_db_provider
            logout:
                path: /logout
                target: /
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/user, roles: ROLE_SUPERADMIN }
    

