# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    app.bundle.entity.menu.class: AppBundle\Entity\TMenu
    app.bundle.service.authorization.class: AppBundle\Service\AuthorizationService

services:
    app.bundle.authorization.service:
      class: %app.bundle.service.authorization.class%
      arguments: ["@doctrine.orm.entity_manager","%app.bundle.entity.menu.class%"]
#    service_name:
#        class: AppBundle\Directory\ClassName "@service_container",
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]