# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    app.bundle.service.authorization.class: AppBundle\Service\AuthorizationService
    app.bundle.service.user.management.class: AppBundle\Service\UserManagementService
    app.bundle.service.customer.management.class: AppBundle\Service\CustomerManagementService


services:
    app.bundle.authorization.service:
      class: %app.bundle.service.authorization.class%
      arguments: ["@doctrine.orm.entity_manager"]
    app.bundle.user.management.service:
      class: %app.bundle.service.user.management.class%
      arguments: ["@doctrine.orm.entity_manager"]
    app.bundle.customer.management.service:
      class: %app.bundle.service.customer.management.class%
      arguments: ["@doctrine.orm.entity_manager"]
    
#     
#    service_name:
#        class: AppBundle\Directory\ClassName "@service_container",
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]