<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Meal extends \AppBundle\Entity\Meal implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Meal' . "\0" . 'mealName', '' . "\0" . 'AppBundle\\Entity\\Meal' . "\0" . 'mealDesc', '' . "\0" . 'AppBundle\\Entity\\Meal' . "\0" . 'mealDescIndo', '' . "\0" . 'AppBundle\\Entity\\Meal' . "\0" . 'mealPrice', '' . "\0" . 'AppBundle\\Entity\\Meal' . "\0" . 'discount', '' . "\0" . 'AppBundle\\Entity\\Meal' . "\0" . 'picture', '' . "\0" . 'AppBundle\\Entity\\Meal' . "\0" . 'mealId', '' . "\0" . 'AppBundle\\Entity\\Meal' . "\0" . 'category'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Meal' . "\0" . 'mealName', '' . "\0" . 'AppBundle\\Entity\\Meal' . "\0" . 'mealDesc', '' . "\0" . 'AppBundle\\Entity\\Meal' . "\0" . 'mealDescIndo', '' . "\0" . 'AppBundle\\Entity\\Meal' . "\0" . 'mealPrice', '' . "\0" . 'AppBundle\\Entity\\Meal' . "\0" . 'discount', '' . "\0" . 'AppBundle\\Entity\\Meal' . "\0" . 'picture', '' . "\0" . 'AppBundle\\Entity\\Meal' . "\0" . 'mealId', '' . "\0" . 'AppBundle\\Entity\\Meal' . "\0" . 'category'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Meal $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setMealName($mealName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMealName', [$mealName]);

        return parent::setMealName($mealName);
    }

    /**
     * {@inheritDoc}
     */
    public function getMealName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMealName', []);

        return parent::getMealName();
    }

    /**
     * {@inheritDoc}
     */
    public function setMealDesc($mealDesc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMealDesc', [$mealDesc]);

        return parent::setMealDesc($mealDesc);
    }

    /**
     * {@inheritDoc}
     */
    public function getMealDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMealDesc', []);

        return parent::getMealDesc();
    }

    /**
     * {@inheritDoc}
     */
    public function setMealDescIndo($mealDescIndo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMealDescIndo', [$mealDescIndo]);

        return parent::setMealDescIndo($mealDescIndo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMealDescIndo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMealDescIndo', []);

        return parent::getMealDescIndo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMealPrice($mealPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMealPrice', [$mealPrice]);

        return parent::setMealPrice($mealPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getMealPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMealPrice', []);

        return parent::getMealPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscount($discount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscount', [$discount]);

        return parent::setDiscount($discount);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscount', []);

        return parent::getDiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function setPicture($picture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPicture', [$picture]);

        return parent::setPicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getPicture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPicture', []);

        return parent::getPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function getMealId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getMealId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMealId', []);

        return parent::getMealId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\AppBundle\Entity\MealCategory $category = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

}
